- hosts: pgw1
  gather_facts: no
  vars_files:
      - vars.yaml
  tasks:
    - name: find dest file name
      become: yes
      become_user: root
      become_method: su
      shell: find {{path.webgui}} -name {{item.key}}
      with_dict:
        - "{{src_files}}"
      register: result
#    - debug: var=result.results

    - set_fact:
        dest_files: "{{ dest_files|default({}) | combine( {item.stdout.split('/')[-1]: item.stdout} ) }}"
      with_items: "{{result.results}}"
      when: item.stdout != ''

#    - debug: var=dest_files

    - name: check dest bak file is exists
      become: yes
      become_user: root
      become_method: su
      stat: path="{{item.value}}.bak"
      with_dict: "{{dest_files}}"
      register: result
#    - debug: var=result

    - name: backup the file
      become: yes
      become_user: root
      become_method: su
      shell: cp -a {{item.item.value}} {{item.item.value}}.bak
      with_items: "{{result.results}}"
      when: item.stat.exists == false

    - name: copy the file
      become: yes
      become_user: root
      become_method: su
      copy: src={{src_files[item.key]}} dest={{dest_files[item.key]}} mode=644 owner=provgw group=provgw
      with_dict: "{{dest_files}}"

    - name: restart pgw
      become: yes
      become_user: root
      become_method: su
      shell: /opt/provgw/tomcat/bin/run_as_provgw.sh restart
      when: is_restart == true
